### ISSUE TITLE
et crashes when --prune is combined with a non existing --glob

### ISSUE THREAD

**Issue by jhscheer** [solidiquis/erdtree#115]
`et` crashes when `--prune` is combined with a non existing `--glob`, e.g.:
```bash
$ cargo run -- --no-config --level 1 --prune --glob "main.rs" tests/data
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/et --no-config --level 1 --prune --glob main.rs tests/data`
thread '<unnamed>' panicked at 'internal error: entered unreachable code: Try to access a freed node', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/indextree-4.6.0/src/node.rs:45:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', src/render/tree/mod.rs:156:24
```

**Comment by solidiquis** [comment]
Thank you. I'll be looking into this
