### ISSUE TITLE
thread panics when called from root ('/') directory

### ISSUE THREAD

**Issue by TomLebeda** [solidiquis/erdtree#31]
I really like this program, just a (small?) issue I found:

when I do `cd /` and then `et`, I get this panic:

```
[tom@tom-pc ~]$ cd /
[tom@tom-pc /]$ et
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/erdtree-1.2.0/src/fs/erdtree/node.rs:220:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/ignore-0.4.20/src/walk.rs:1302:31
^C
```

**Comment by solidiquis** [comment]
Thank you bringing this to my attention! I just merged in a fix and will include it in the next minor version bump later today. Again tysm! :]
